---
title: "Publications"
---

Kindig, David, Jenna Nobles, and Moheb Zidan. 2018. “Meeting the Institute of Medicine’s 2030 Us Life Expectancy Target.” American Journal of Public Health 108(1): 87-92. PMCID 5719677.

Nobles, Jenna, Amar Hamoudi, R. Nowak, E. Landau, A. Baron, J. Brittingham, and B. Mason. 2018.  “Place-Based Variation in Early Pregnancy Loss: Evidence from Population Data.” 25: 278a-79a. PMCID.

Valentine, Jessa, Brad Barham, Seth Gitter, and Jenna Nobles. 2017. “Migration and the Pursuit of Education in Southern Mexico.” Comparative Education Review 61(1): 141-75. PMCID 984723.

Seltzer, Nathan, and Jenna Nobles. 2017. “Post-Disaster Fertility: Hurricane Katrina and the Changing Racial Composition of New Orleans.” Population and Environment 38(4): 465-90. PMCID 5703431.

Nobles, Jenna, Luis Rubalcava, and Graciela Teruel. 2015. “After Spouses Depart: Emotional Wellbeing among Nonmigrant Mexican Mothers.” Social Science & Medicine 132: 236-44. PMCID 4562970.

Nobles, Jenna, Elizabeth Frankenberg, and Duncan Thomas. 2015. “The Effects of Mortality on Fertility: Population Dynamics after a Natural Disaster.” Demography 52(1): 15-38. PMCID 4411230.

Nobles, Jenna, and Christopher McKelvey. 2015. “Gender, Power, and Emigration from Mexico.” Demography 52(5): 1573-600. PMCID 4607611.

Zhang, Xiao, Ana Martinez-Donate, Jenna Nobles, Melbourne Hovell, Maria Rangel, and Natalie Rhoads. 2015. “Substance Use across Different Phases of the Migration Process: A Survey of Mexican Migrants Flows.” Journal of Immigrant and Minority Health 17(6): 1746-57. PMCID 4506267.

Hamoudi, Amar, and Jenna Nobles. 2014. “Do Daughters Really Cause Divorce? Stress, Pregnancy, and Family Composition.” Demography 51(4): 1423-49. PMCID 4411232.

Nobles, Jenna. 2013. “Migration and Father Absence: Shifting Family Structure in Mexico.” Demography 50(4): 1303-1314.

Frankenberg, Elizabeth, Jenna Nobles, and Cecep Sumantri. 2012. “Community Destruction and Traumatic Stress in Post-Tsunami Indonesia.” Journal of Health and Social Behavior 53(4): 500-516.